export interface PostComment {
  id: number;
  author: string;
  avatar: string;
  content: string;
}

export interface Post {
  id: number;
  author: string;
  avatar: string;
  time: string;
  route: string;
  content: string;
  likes: number;
  likedBy: string[];
  comments: PostComment[];
}

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  answerIndex: number;
  explanation: string;
}

export interface BusLocation {
  id: string;
  route: string;
  direction: string;
  lat: number;
  speed: number;
  stops: string[];
  currentStopIndex: number;
  passengers: number;
  capacity: number;
  minutesToArrive: number;
}

export type AppLanguage = "zh" | "en" | "th" | "vi" | "hakka" | "ja" | "ko";

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  zh: {
    appName: "風城通",
    appSubtitle: "終極智慧交通一站式 App",
    userLevel: "大學生 • 風城等級 12",
    windAlert: "強風警報",
    bannerTitle: "強風特報：九降風來襲",
    bannerDesc: "目前瞬間陣風達 8 級，騎乘 uBike 請注意安全。",
    searchPlaceholder: "今天要去哪裡？(清華大學、巨城...)",
    commuteTitle: "即時通勤狀態",
    updateTime: "更新於 1 分鐘前",
    routeLabel: "路線",
    bus1Dest: "往 高鐵新竹站",
    seatPlenty: "座位充裕",
    minLabel: "分鐘",
    viewMap: "查看即時地圖",
    transferHub: "轉乘樞紐",
    ubikeStation: "uBike 2.0 新竹市府站",
    liveSlots: "即時車位",
    canBorrow: "可借車",
    canReturn: "可還位",
    openOfficial: "開啟官方資訊",
    traHsinchu: "台鐵新竹站",
    traStatus: "準點運行",
    viewSchedule: "時刻表查詢",
    hsrLiujia: "高鐵六家站",
    hsrStatus: "每 20 分一班",
    bookTicket: "官方訂票",
    travelTitle: "推薦旅遊景點",
    hotSpot: "熱門景點",
    attractionTemple: "新竹城隍廟",
    attractionTempleDesc: "探索全台最高位階城隍廟與在地美食小吃。",
    attractionHarbor: "南寮漁港 (十七公里海岸)",
    attractionHarborDesc: "地中海風格建築與絕美夕陽，放風箏的好去處。",
    rewardsTitle: "優惠獎勵",
    ptsLabel: "目前點數: 1,240 Pts",
    viewAll: "查看全部",
    claimReward: "領取兌換",
    pointsExchange: "點數兌換",
    bigCityDiscount: "Big City 巨城購物中心 - 當日停車折抵 1 小時",
    cakeDiscount: "春上布丁蛋糕 - 任選蛋糕 9 折",
    socialTitle: "社群互動 & 遊戲",
    quizTitle: "交通益智王 - 挑戰賺點",
    quizDesc: "累積答對領大紅包，挑戰全球排行榜",
    leaderboardTitle: "搭乘時數榜",
    leaderboardWeekly: "本週搭乘榜",
    friendsMap: "好友地圖",
    friendsOnline: "3 人在線",
    addFriend: "+ 加好友",
    likeBtn: "讚",
    commentBtn: "留言",
    shareBtn: "分享",
    systemSettings: "系統設定",
    langSettings: "語言設定 Language",
    fontSizeSettings: "字體大小調整",
    previewText: "預覽文字內容展示",
    pushSettings: "智慧通知推播",
    pushDesc: "包含誤點提醒與即時天氣預警",
    bottomHome: "首頁",
    bottomTransfer: "轉乘",
    bottomRewards: "優惠",
    bottomSocial: "社群",
    bottomSettings: "設定",
    helperTitle: "AI 智慧交通導遊",
    helperPlaceholder: "輸入問題來問我（如：新竹城隍廟有什麼美食？）」",
    askHelper: "詢問 AI 助理",
    chatting: "AI 分析中...",
    scanTitle: "掃描乘車 QR Code",
    scanPrompt: "請將 QR Code 置於框內",
    successMsg: "成功！已領取 50 Pts 風城點數"
  },
  en: {
    appName: "Windy City Transit",
    appSubtitle: "Ultimate Smart All-in-One App",
    userLevel: "College Student • Level 12",
    windAlert: "High Wind Alert",
    bannerTitle: "Wind Alert: Windy City Gales",
    bannerDesc: "Gales reaching Level 8. Double-grip handlebars if riding YouBike.",
    searchPlaceholder: "Where are you heading? (NTHU, Big City...)",
    commuteTitle: "Real-time Transit Status",
    updateTime: "Updated 1 min ago",
    routeLabel: "Route",
    bus1Dest: "To HSR Hsinchu Station",
    seatPlenty: "Plenty of Seats",
    minLabel: "min",
    viewMap: "View Real-time Map",
    transferHub: "Transfer Hub",
    ubikeStation: "YouBike 2.0 City Hall Station",
    liveSlots: "Live Status",
    canBorrow: "Bikes Available",
    canReturn: "Empty Docks",
    openOfficial: "Open Official Site",
    traHsinchu: "TRA Hsinchu Station",
    traStatus: "On Time",
    viewSchedule: "Check Timetable",
    hsrLiujia: "HSR Liujia Station",
    hsrStatus: "Every 20 mins",
    bookTicket: "Book Ticket",
    travelTitle: "Recommended Attractions",
    hotSpot: "Popular Spot",
    attractionTemple: "Hsinchu City God Temple",
    attractionTempleDesc: "Explore the highest-ranked historical temple and local gourmet snacks.",
    attractionHarbor: "Nanliao Harbor (17km Coastline)",
    attractionHarborDesc: "Mediterranean architecture, stunning sunsets, and nice breeze for kite-flying.",
    rewardsTitle: "My Rewards",
    ptsLabel: "My Balance: 1,240 Pts",
    viewAll: "View All",
    claimReward: "Claim Reward",
    pointsExchange: "Exchange Points",
    bigCityDiscount: "Big City Mall - 1 Hour Free Parking Ticket",
    cakeDiscount: "Chun Sun Pudding Cake - 10% Off Any Cake",
    socialTitle: "Social Feed & Trivia",
    quizTitle: "Transit Trivia-Win Points",
    quizDesc: "Answer correctly to win lucky red envelopes and see hierarchy.",
    leaderboardTitle: "Commuter Board",
    leaderboardWeekly: "Weekly Leaderboard",
    friendsMap: "Friends Map",
    friendsOnline: "3 Active Friends",
    addFriend: "+ Add Friend",
    likeBtn: "Like",
    commentBtn: "Comment",
    shareBtn: "Share",
    systemSettings: "System Settings",
    langSettings: "Language Settings Selection",
    fontSizeSettings: "Font Size Control",
    previewText: "Preview Content Display Text",
    pushSettings: "Smart Push Notification",
    pushDesc: "Includes delay warnings and live weather forecasts",
    bottomHome: "Home",
    bottomTransfer: "Transfer",
    bottomRewards: "Rewards",
    bottomSocial: "Social",
    bottomSettings: "Settings",
    helperTitle: "AI Smart Transit Guide",
    helperPlaceholder: "Ask something (e.g. Recommended snacks at God Temple?)...",
    askHelper: "Ask AI Guide",
    chatting: "AI Analyzing...",
    scanTitle: "Scan Transit QR Code",
    scanPrompt: "Position QR Code inside the frame",
    successMsg: "Success! You earned 50 Pts commuter reward."
  },
  th: {
    appName: "วินดี้ซิตี้ทรานซิท",
    appSubtitle: "แอพพลิเคชั่นการเดินทางอัจฉริยะแบบครบวงจร",
    userLevel: "นักศึกษามหาวิทยาลัย • เลเวล 12",
    windAlert: "เตือนลมแรง",
    bannerTitle: "แจ้งเตือนลมพายุเก้าระดับ",
    bannerDesc: "กระแสลมแรงระดับ 8 โปรดจับแฮนด์ YouBike ให้แน่นและระวัง",
    searchPlaceholder: "วันนี้คุณจะไปไหน? (ม.ชิงหัว, บิ๊กซิตี้...)",
    commuteTitle: "สถานะเที่ยวเดินรถสด",
    updateTime: "อัปเดตเมื่อ 1 นาทีที่แล้ว",
    routeLabel: "สายรถ",
    bus1Dest: "ไป สถานีรถไฟความเร็วสูงซินจู๋",
    seatPlenty: "มีที่นั่งว่างจำนวนมาก",
    minLabel: "นาที",
    viewMap: "ดูแผนที่สด",
    transferHub: "ศูนย์เปลี่ยนถ่ายการเดินทาง",
    ubikeStation: "YouBike 2.0 ศาลากลางซินจู๋",
    liveSlots: "สถานะสด",
    canBorrow: "จักรยานว่าง",
    canReturn: "ช่องจอดว่าง",
    openOfficial: "เปิดข้อมูลทางการ",
    traHsinchu: "สถานีรถไฟซินจู๋ TRA",
    traStatus: "ตรงเวลา",
    viewSchedule: "ตรวจสอบตารางเวลา",
    hsrLiujia: "สถานีรถไฟความเร็วสูง หลิวเจีย",
    hsrStatus: "ออกทุกๆ 20 นาที",
    bookTicket: "จองตั๋วออนไลน์",
    travelTitle: "สถานที่ท่องเที่ยวแนะนำ",
    hotSpot: "ยอดนิยม",
    attractionTemple: "ศาลเจ้าพ่อหลักเมืองซินจู๋",
    attractionTempleDesc: "เยี่ยมชมจุดศูนย์รวมศรัทธาที่ใหญ่ที่สุดและลิ้มลองของอร่อยในท้องถิ่น",
    attractionHarbor: "ท่าเรือหนานเหลียว (ชายหาด 17 กม.)",
    attractionHarborDesc: "สถาปัตยกรรมสไตล์เมดิเตอร์เรเนียน ชมพระอาทิตย์ตกดิน และจุดเล่นว่าวที่ยอดเยี่ยม",
    rewardsTitle: "รางวัลและสิทธิพิเศษ",
    ptsLabel: "คะแนนสะสม: 1,240 Pts",
    viewAll: "ดูทั้งหมด",
    claimReward: "แลกรางวัล",
    pointsExchange: "แลกของรางวัล",
    bigCityDiscount: "ห้างสรรพสินค้าบิ๊กซิตี้ - ฟรีบัตรจอดรถ 1 ชั่วโมง",
    cakeDiscount: "เค้กพุดดิ้งชุนซัน - ส่วนลดเค้ก 10%",
    socialTitle: "ฟีดโซเชียลและเกมตอบปัญหา",
    quizTitle: "ราชานักเดินทาง - ตอบคว้าแต้ม",
    quizDesc: "สะสมตอบถูกชิงรางวัลใหญ่อั่งเปาและท้าทายตารางคะแนน",
    leaderboardTitle: "บอร์ดนักเดินทางตัวยง",
    leaderboardWeekly: "อันดับผู้ใช้ประจำสัปดาห์",
    friendsMap: "แผนที่เพื่อนพ้อง",
    friendsOnline: "มีเพื่อออนไลน์ 3 คน",
    addFriend: "+ เพิ่มเพื่อน",
    likeBtn: "ถูกใจ",
    commentBtn: "ความคิดเห็น",
    shareBtn: "แชร์",
    systemSettings: "ตั้งค่าระบบ",
    langSettings: "ภาษาพาสิทธิ์ Language",
    fontSizeSettings: "ปรับแต่งขนาดตัวอักษร",
    previewText: "ตัวอย่างการอักษรสำหรับแสดงผล",
    pushSettings: "เปิดแจ้งเตือนพุชอัจฉริยะ",
    pushDesc: "รวมถึงคำเตือนความล่าช้าและการพยากรณ์พายุสด",
    bottomHome: "หน้าแรก",
    bottomTransfer: "เปลี่ยนรถ",
    bottomRewards: "รางวัล",
    bottomSocial: "โซเชียล",
    bottomSettings: "ตั้งค่า",
    helperTitle: "AI แนะนำการเดินทางอัจฉริยะ",
    helperPlaceholder: "พิมพ์คำถามที่ต้องการถาม...",
    askHelper: "ปรึกษาไกด์ AI",
    chatting: "AI กำลังกำลังวิเคราะห์...",
    scanTitle: "สแกนคิวอาร์โค้ดเดินทาง",
    scanPrompt: "วางคิวอาร์ให้อยู่ในกรอบ",
    successMsg: "สำเร็จแล้ว! คุณได้รับโบนัสแต้ม 50 Pts"
  },
  vi: {
    appName: "Giao thông Phong Thành",
    appSubtitle: "Ứng dụng giao thông thông minh một điểm dừng",
    userLevel: "Sinh viên • Cấp độ Phong Thành 12",
    windAlert: "Cảnh báo gió lớn",
    bannerTitle: "Tin bão gió: Hiện tượng gió Cửu Giáng",
    bannerDesc: "Gió giật lên tới cấp 8. Hãy nắm chắc tay lái khi đi xe YouBike.",
    searchPlaceholder: "Hôm nay bạn muốn đi đâu? (ĐH Thanh Hoa, Big City...)",
    commuteTitle: "Trạng thái giao thông trực tiếp",
    updateTime: "Đã cập nhật 1 phút trước",
    routeLabel: "Tuyến",
    bus1Dest: "Đi ga tàu cao tốc Hsinchu",
    seatPlenty: "Chỗ ngồi rộng rãi",
    minLabel: "phút",
    viewMap: "Xem bản đồ trục tiếp",
    transferHub: "Trung tâm chuyển tuyến",
    ubikeStation: "YouBike 2.0 Nhà thị chính Hsinchu",
    liveSlots: "Trạng thái trực tiếp",
    canBorrow: "Xe có sẵn",
    canReturn: "Khe trống để trả",
    openOfficial: "Mở thông tin chính thức",
    traHsinchu: "Ga tàu hoả Hsinchu TRA",
    traStatus: "Đúng giờ",
    viewSchedule: "Tra cứu lịch trình",
    hsrLiujia: "Ga tàu cao tốc Liujia",
    hsrStatus: "20 phút một chuyến",
    bookTicket: "Đặt vé chính thức",
    travelTitle: "Địa điểm du lịch gợi ý",
    hotSpot: "Điểm nổi bật",
    attractionTemple: "Đền Thành Hoàng Hsinchu",
    attractionTempleDesc: "Khám phá ngôi đền linh thiêng bậc nhất và ẩm thực đường phố đặc trưng.",
    attractionHarbor: "Cảng cá Nam Liêu (bờ biển 17km)",
    attractionHarborDesc: "Kiến trúc phong cách Địa Trung Hải, hoàng hôn siêu đẹp và là nơi thả diều hấp dẫn.",
    rewardsTitle: "Ưu đãi & Điểm thưởng",
    ptsLabel: "Điểm hiện tại: 1,240 Pts",
    viewAll: "Xem tất cả",
    claimReward: "Đổi quà",
    pointsExchange: "Đổi điểm quà",
    bigCityDiscount: "Big City - Vé đỗ xe miễn phí 1 giờ",
    cakeDiscount: "Bánh bông lan Chun Sun - Giảm giá 10% bánh",
    socialTitle: "Tương tác Cộng đồng & Đố vui",
    quizTitle: "Đố vui giao thông tích điểm",
    quizDesc: "Trả lời đúng liên tục để nhận thưởng bao lì lì và đứng đầu bảng xếp hạng",
    leaderboardTitle: "Xếp hạng hành trình",
    leaderboardWeekly: "Bảng xếp hạng tuần",
    friendsMap: "Bản đồ bạn bè",
    friendsOnline: "3 người trực tuyến",
    addFriend: "+ Thêm bạn",
    likeBtn: "Thích",
    commentBtn: "Bình luận",
    shareBtn: "Chia sẻ",
    systemSettings: "Cài đặt hệ thống",
    langSettings: "Cài đặt Ngôn ngữ Language",
    fontSizeSettings: "Điều chỉnh kích cỡ phông",
    previewText: "Văn bản xem trước thử nghiệm hiển thị",
    pushSettings: "Bật thông báo thông minh",
    pushDesc: "Gồm báo cáo gián đoạn tàu xe và cảnh báo thời tiết khẩn cấp",
    bottomHome: "Trang chủ",
    bottomTransfer: "Chuyển tiếp",
    bottomRewards: "Ưu đãi",
    bottomSocial: "Xã hội",
    bottomSettings: "Cài đặt",
    helperTitle: "AI Trực tuyến Du lịch Giao thông",
    helperPlaceholder: "Nhập câu hỏi tại đây...",
    askHelper: "Hỏi AI Hướng Dẫn",
    chatting: "AI đang phân tích...",
    scanTitle: "Quét mã QR phương tiện",
    scanPrompt: "Hãy đặt mã QR trong khung",
    successMsg: "Thành công! Bạn cộng được 50 Pts thưởng xanh"
  },
  hakka: {
    appName: "風城智慧交通通 (Hakka)",
    appSubtitle: "終極智慧交通一站式 App",
    userLevel: "大專生 • 風城等級 12",
    windAlert: "強風警報 (Gió khiong)",
    bannerTitle: "強風特報：九降風來襲 (Kiú-kong-fûng)",
    bannerDesc: "目前瞬間強風達八級，騎 uBike 著愛特別注意安全捏。",
    searchPlaceholder: "今日老弟想去底角？(清華大學、巨城...)",
    commuteTitle: "即時通勤狀態",
    updateTime: "更新於 1 分鐘前",
    routeLabel: "路線",
    bus1Dest: "往 高鐵新竹站",
    seatPlenty: "位仔盡多",
    minLabel: "分鐘",
    viewMap: "看即時地圖",
    transferHub: "轉車大中心",
    ubikeStation: "uBike 2.0 新竹市府站",
    liveSlots: "即時車位仔",
    canBorrow: "做得借車",
    canReturn: "做得還位",
    openOfficial: "開啟官方資訊",
    traHsinchu: "台鐵新竹站",
    traStatus: "準時開車 (Chún-sṳ̀)",
    viewSchedule: "時刻表查詢",
    hsrLiujia: "高鐵六家站",
    hsrStatus: "每 20 分一班",
    bookTicket: "官方訂票",
    travelTitle: "推荐旅遊好景點",
    hotSpot: "當紅景點",
    attractionTemple: "新竹城隍廟",
    attractionTempleDesc: "探索全臺灣最高位階城隍廟同客家在地美食小點。",
    attractionHarbor: "南寮漁港 (十七公里海岸)",
    attractionHarborDesc: "地中海風格建築同絕靚夕陽，放風吹个好土地。",
    rewardsTitle: "特惠獎勵",
    ptsLabel: "目前點數: 1,240 Pts",
    viewAll: "看全部",
    claimReward: "領拿預兌",
    pointsExchange: "點數換拿",
    bigCityDiscount: "Big City 巨城購物中心 - 當日停車折抵 1 點鐘",
    cakeDiscount: "春上布丁蛋糕 - 任選布丁蛋糕打 9 折",
    socialTitle: "社群打交道同交通益智",
    quizTitle: "交通益智王 - 擂台拿分",
    quizDesc: "累積答著領大紅包袋，挑戰全球英雄榜首",
    leaderboardTitle: "搭乘時數榜",
    leaderboardWeekly: "本週搭乘時數表",
    friendsMap: "好朋友地圖",
    friendsOnline: "3 人在大線上",
    addFriend: "+ 結交好友",
    likeBtn: "按讚",
    commentBtn: "講幾句仔",
    shareBtn: "向大家分流",
    systemSettings: "系統設定",
    langSettings: "語言設定 Language",
    fontSizeSettings: "字體大細調整",
    previewText: "預覽客家文字內容展示",
    pushSettings: "智慧通知推播",
    pushDesc: "包含誤點提醒同即時九降風天色預警",
    bottomHome: "首頁",
    bottomTransfer: "轉乘",
    bottomRewards: "優惠",
    bottomSocial: "社群",
    bottomSettings: "設定",
    helperTitle: "AI 客家智慧交通導師",
    helperPlaceholder: "輸入問題來問我（比如：新竹城隍廟有哪兜客家美食？））",
    askHelper: "問 AI 交通導助",
    chatting: "AI 科學分析中...",
    scanTitle: "掃描乘車 QR 條碼",
    scanPrompt: "請把 QR Code 囥放兜框內",
    successMsg: "成功！領到 50 Pts 風城獎勵點數"
  },
  ja: {
    appName: "風城通 (Hsinchu Go)",
    appSubtitle: "ワンストップ・スマート交通アプリ",
    userLevel: "大学生 • 風城レベル 12",
    windAlert: "強風警報",
    bannerTitle: "強風速報：九降風接近中",
    bannerDesc: "突風レベル8。YouBike乗車時は安全に注意してください。",
    searchPlaceholder: "今日はどこへ行きますか？(清華大学、ビッグシティ...)",
    commuteTitle: "リアルタイム通勤ステータス",
    updateTime: "1分前に更新",
    routeLabel: "路線",
    bus1Dest: "高鐵新竹駅行き",
    seatPlenty: "空席あり",
    minLabel: "分",
    viewMap: "リアルタイム地図表示",
    transferHub: "乗換ハブ",
    ubikeStation: "YouBike 2.0 新竹市役所駅",
    liveSlots: "リアルタイム駐車状況",
    canBorrow: "貸出可能",
    canReturn: "返却可能",
    openOfficial: "公式サイトを開く",
    traHsinchu: "台鉄新竹駅",
    traStatus: "定刻運行",
    viewSchedule: "時刻表検索",
    hsrLiujia: "高鉄六家駅",
    hsrStatus: "20分おきに運行",
    bookTicket: "公式予約",
    travelTitle: "おすすめ観光スポット",
    hotSpot: "人気スポット",
    attractionTemple: "新竹城隍廟",
    attractionTempleDesc: "台湾最高位の城隍廟と地元の美味しいB級グルメをめぐる。",
    attractionHarbor: "南寮漁港 (17km海岸線)",
    attractionHarborDesc: "地中海風の建築と絶景の夕日。凧揚げに絶好の場所。",
    rewardsTitle: "特典・ギフト",
    ptsLabel: "現在のポイント: 1,240 Pts",
    viewAll: "すべて表示",
    claimReward: "特典交換",
    pointsExchange: "ポイント交換",
    bigCityDiscount: "Big City ビッグシティ - 当日駐車場1時間無料",
    cakeDiscount: "春上プリンケーキ - ケーキ全品10%OFF",
    socialTitle: "コミュニティとゲーム",
    quizTitle: "交通クイズ王 - ポイント獲得チャレンジ",
    quizDesc: "連続正解で赤いお年玉袋を獲得して、グローバルランキングに挑戦",
    leaderboardTitle: "乗車時間ランキング",
    leaderboardWeekly: "今週の乗車数表",
    friendsMap: "フレンドマップ",
    friendsOnline: "3人オンライン",
    addFriend: "+ フレンド追加",
    likeBtn: "いいね",
    commentBtn: "コメント",
    shareBtn: "シェア",
    systemSettings: "システム設定",
    langSettings: "言語設定 Language",
    fontSizeSettings: "フォントサイズ調整",
    previewText: "日本語表示文字のプレビュー",
    pushSettings: "スマートプッシュ通知",
    pushDesc: "遅延アラートとリアルタイムの気象警告を含む",
    bottomHome: "ホーム",
    bottomTransfer: "乗換",
    bottomRewards: "特典",
    bottomSocial: "コミュニティ",
    bottomSettings: "設定",
    helperTitle: "AIスマート交通ガイド",
    helperPlaceholder: "質問を入力してください (例: 城隍廟のグルメは？)...",
    askHelper: "AIガイドに聞く",
    chatting: "AI分析中...",
    scanTitle: "乗車QRコード読み取り",
    scanPrompt: "枠の中にQRコードを入れてください",
    successMsg: "成功しました！50 Ptsの報酬ポイントを獲得しました"
  },
  ko: {
    appName: "풍성통 (Hsinchu Transit)",
    appSubtitle: "원스톱 스마트 교통 앱",
    userLevel: "대학생 • 풍성 레벨 12",
    windAlert: "강풍 경보",
    bannerTitle: "강풍 특보: 구강풍 내습",
    bannerDesc: "현재 순간 돌풍 8단계. YouBike 이용 시 항상 주의하세요.",
    searchPlaceholder: "오늘 어디로 가시나요? (청화대학교, 빅시티...)",
    commuteTitle: "실시간 통근 상태",
    updateTime: "1분 전 업데이트",
    routeLabel: "노선",
    bus1Dest: "고속철도 신주역 행",
    seatPlenty: "좌석 여유",
    minLabel: "분",
    viewMap: "실시간 지도 보기",
    transferHub: "환승 허브",
    ubikeStation: "YouBike 2.0 신주시청역",
    liveSlots: "실시간 주차 상황",
    canBorrow: "대여 가능",
    canReturn: "반납 가능",
    openOfficial: "공식 사이트 열기",
    traHsinchu: "코레일 신주역",
    traStatus: "정시 운행",
    viewSchedule: "시간표 조회",
    hsrLiujia: "고속철도 류자역",
    hsrStatus: "20분 간격 운행",
    bookTicket: "공식 예매",
    travelTitle: "추천 관광지",
    hotSpot: "인기 관광지",
    attractionTemple: "신주 성황묘",
    attractionTempleDesc: "대만에서 가장 격식 높은 성황묘와 현지 정통 맛집 탐방.",
    attractionHarbor: "난랴오 어항 (17km 해안선)",
    attractionHarborDesc: "지중해풍 그리스 스타일 건축과 아름다운 노을, 연날리기의 명소.",
    rewardsTitle: "이벤트 및 포인트",
    ptsLabel: "현재 포인트: 1,240 Pts",
    viewAll: "모두 보기",
    claimReward: "포인트 교환",
    pointsExchange: "포인트 교환 상품",
    bigCityDiscount: "Big City 빅시티 쇼핑몰 - 당일 주차 1시간 제휴 등록",
    cakeDiscount: "춘상 푸딩 케이크 - 전 품목 10% 가격 할인",
    socialTitle: "소통 및 교통 퀴즈",
    quizTitle: "교통 장학 퀴즈 - 포인트 적립",
    quizDesc: "연속 정답 시 세뱃돈 보너스를 획득하고 글로벌 명예의 전당 도전",
    leaderboardTitle: "탑승 시간 랭킹",
    leaderboardWeekly: "이번 주 탑승 통계",
    friendsMap: "친구 실시간 지도",
    friendsOnline: "3명 접속 중",
    addFriend: "+ 친구 추가",
    likeBtn: "좋아요",
    commentBtn: "댓글",
    shareBtn: "공유",
    systemSettings: "시스템 설정",
    langSettings: "언어 설정 Language",
    fontSizeSettings: "글자 크기 조절",
    previewText: "선택된 글꼴 크기 미리보기",
    pushSettings: "지능형 푸시 알림",
    pushDesc: "버스 지연 경보 및 실시간 기상 이변 경보 알림",
    bottomHome: "홈",
    bottomTransfer: "환승",
    bottomRewards: "혜택",
    bottomSocial: "커뮤니티",
    bottomSettings: "설정",
    helperTitle: "AI 스마트 교통 가이드",
    helperPlaceholder: "무엇이든 물어보세요 (예: 성황묘 맛집 추천?)...",
    askHelper: "AI 가이드 질문",
    chatting: "AI 분석 중...",
    scanTitle: "탑승 QR 코드 스캔",
    scanPrompt: "사각 프레임 안에 QR 코드를 맞춰주세요",
    successMsg: "성공! 50 Pts 승차 보너스가 적립되었습니다."
  }
};
